_commit: 1e44846e8d8e5d17f333138c2fbd9e54d57c7468
_src_path: https://github.com/ORINOCO-Lite/orinoco-lite-template.git
project_slug: dev-centerforopenneuroscience.org
project_name: Center for Open Neuroscience
site_base_url: https://dev.centerforopenneuroscience.org/
site_description: The Center for Open Neuroscience brings open practices into the
  everyday work of neuroscience.
pr_previews: netlify
include_site_specific: false
pages_history_limit: 3
