_commit: v0.3.0rc3
_src_path: gh:ORINOCO-Lite/orinoco-lite-template
project_name: Center for Open Neuroscience
project_slug: dev-centerforopenneuroscience.org
site_description: The Center for Open Neuroscience brings open practices into the
  everyday work of neuroscience.
site_base_url: https://dev.centerforopenneuroscience.org/
pr_previews: netlify

