version: 1
record_prefix: "xyzrins:"
identity:
  title: Center for Open Neuroscience
  description: The Center for Open Neuroscience brings open practices into the everyday work of neuroscience.
  base_url: https://dev.centerforopenneuroscience.org/
navigation:
  - name: People
    page_ref: /persons/
    weight: 10
  - name: Projects
    page_ref: /projects/
    weight: 25
  - name: Publications
    page_ref: /publications/
    weight: 30
  - name: Instruments
    page_ref: /instruments/
    weight: 36
  - name: Explore
    page_ref: /explore/
    weight: 40
footer_navigation:
  - name: Contact
    page_ref: /contact/
presentation:
  color_scheme: con
  default_appearance: light
  header_layout: basic
